# Generated by Django 3.2.8 on 2021-11-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_preference_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='video_url_left',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='video_url_right',
        ),
        migrations.AlterField(
            model_name='preference',
            name='label',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, max_digits=2, null=True, verbose_name='preference label'),
        ),
    ]
