# Generated by Django 3.2.9 on 2021-11-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_auto_20211106_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='response_timestamp',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='shown_to_human_timestamp',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='updated_timestamp',
        ),
        migrations.AddField(
            model_name='preference',
            name='priority',
            field=models.IntegerField(db_index=True, default=0, verbose_name='priority'),
        ),
    ]
