# Generated by Django 3.2.8 on 2021-11-05 15:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4(), verbose_name='query_uuid'),
            preserve_default=False,
        ),
    ]
